title: Minimal theme
logo: /assets/img/logo.png
description: Minimal is a theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
encoding: "utf-8"

author:
  name             : "Dr."
  avatar           : "/fig/xingming" # path of avatar image, e.g. "/assets/images/bio-photo.jpg"
  bio              : "."
  location         : "San Jose, USA"
  email            :
  links:
    - label: "Linkedin"
      icon: "fab fa-fw fa-linkedin-in"
      url: "https://www.linkedin.com/in/kejian/"
    - label: "Google Scholar"
      icon: "fa fa-graduation-cap"
      url: "https://scholar.google.com/citations?user=m_Xw6ioAAAAJ&hl=en"
