#!/bin/sh
#chmod +x cibuild
set -e

bundle exec jekyll build
bundle exec htmlproofer ./_site --check-html --check-sri --allow_hash_href --empty_alt_ignore --assume_extension --disable_external ./_site
bundle exec rubocop -D --config .rubocop.yml
bundle exec script/validate-html
gem build jekyll-theme-minimal.gemspec
